---
- hosts: all
  become: true
  tasks:
  - name: Install dependencies for Docker
    yum:
      name: yum-utils
      state: present

  - name: Add Docker repository
    command: yum-config-manager --add-repo  https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install Docker
    yum: 
      name: "{{ packages }}"
      state: present
    vars:
      packages:
      - docker-ce
      - docker-ce-cli 
      - containerd.io
    
  - name: Start & enable Docker service
    ansible.builtin.service:
      name: docker
      state: started
      enabled: yes

  - name: Remove swapfile from /etc/fstab
    mount:
      name: "{{ item }}"
      fstype: swap
      state: absent
    with_items:
      - swap
      - none

  - name: Disable swap
    command: swapoff -a && sed -i '/swap/d' /etc/fstab
    when: ansible_swaptotal_mb > 0

  - name: cgroup
    shell: |
       cat > /tmp/temp.file << EOF 
        {
         "exec-opts": ["native.cgroupdriver=systemd"]
           }
        EOF
  - name: Start & enable Docker service
    ansible.builtin.service:
      name: docker
      state: restarted
      enabled: yes

  - name: Disable SELinux
    command: setenforce 0

  - name: Add YUM repository for Kubernetes
    ansible.builtin.copy:
      src: kubernetes.repo
      dest: /etc/yum.repos.d/kubernetes.repo

  - name: Install Kubernetes
    yum: 
      name: "{{ packages }}"
      state: present
      update_cache: yes
    vars:
      packages:
        - kubelet 
        - kubeadm 
        - kubectl

  - name: start kubelet
    service:
      name: kubelet
      daemon_reload: yes
      state: started

  - name: SELinux
    shell: |
       sudo setenforce 0
      # sudo sed -i ‘s/^SELINUX=enforcing$/SELINUX=permissive/’ /etc/selinux/config

  - name: IPtables
    shell: |
      cat <<EOF > /etc/sysctl.d/k8s.conf
      net.bridge.bridge-nf-call-ip6tables = 1
      net.bridge.bridge-nf-call-iptables = 1
      EOF
      sysctl --system
  
  
  - name: Initialize the Kubernetes cluster using kubeadm command
    when: inventory_hostname in groups['k8s-master']
    command: kubeadm init --pod-network-cidr=10.244.0.0/16

  - name: Set up Kubernetes for  user
    command: "{{ item }}"
    when: inventory_hostname in groups['k8s-master']
    with_items:
    - mkdir -p $HOME/.kube
    - sudo cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
    - sudo chown $(id -u):$(id -g) $HOME/.kube/config

  - name: Install Flannel pod network
    become: false
    when: inventory_hostname in groups['k8s-master']
    command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml

  - name: Retrieve Kubernetes join command that is used to join worker node(s)
    become: false
    when: inventory_hostname in groups['k8s-master']
    command: kubeadm token create --print-join-command
    register: join_command

  - name: Attach kubeadm join command to a file on Ansible control node
    when: inventory_hostname in groups['k8s-master']
    local_action: "copy content='{{ join_command.stdout_lines[0] }}' dest=join-command"

  - name: Copy the join-command file created above to worker node
    when: inventory_hostname in groups['k8s-worker']
    copy: src=join-command dest=/tmp/kubeadm-join.sh mode=0777

  - name: Join the worker node to cluster
    when: inventory_hostname in groups['k8s-worker']
    command: sh /tmp/kubeadm-join.sh
